# admin/kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: admin-service # Name of Kubernetes Service
  labels:
    app: admin
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80 # The port the Service will listen on (for the LoadBalancer)
      targetPort: 8000 # The port the Flask app listens on inside the container
      name: http # Name needed
  type: LoadBalancer # This will provision an external IP address
