# kubernetes/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of base resource files to include
resources:
  - deployment.yaml # Relative path within the 'base' directory
  - service.yaml    # Relative path within the 'base' directory

# This section tells Kustomize to manage image tags
# The 'name' here should match the full image name *without* the tag
# The 'newTag' here is a placeholder that your Cloud Build step will overwrite
images:
  - name: europe-north2-docker.pkg.dev/$PROJECT_ID/nfc-images/receiver
    newTag: latest # This will be replaced by your Cloud Build step
