# Test1/kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: receiver-service # Name of Kubernetes Service
  labels:
    app: receiver
spec:
  selector:
    app: receiver 
  ports:
    - protocol: TCP
      port: 80 # The port the Service will listen on 
      targetPort: 8000 # The port the Flask app listens on inside the container
      name: http # Name needed
  type: ClusterIP # Can change to LoadBalancer for testing
